### ISSUE TITLE
完成所有依赖项的添加和代码复制后，用Qt构建vis_gui失败

### ISSUE THREAD

**Issue by geoexploring** [cjh3020889729/The-PaddleX-QT-Visualize-GUI#1]
您好，按照您b站视频的介绍，完成所有依赖项的添加和代码复制后，用Qt构建vis_gui失败。报出如下的错：

![Screenshot_2](https://user-images.githubusercontent.com/58645709/146633961-5991c528-a8e4-418e-872c-02d9412d75e8.png)

主要的错都是在`C:\Qt\Qt5.14.2\Tools\mingw730_64\lib\gcc\x86_64-w64-mingw32\7.3.0\include\c++`里的，请问您知道是什么原因吗？

谢谢！

**Comment by geoexploring** [comment]
当选择`Qt 5.14.2 MinGW 32-bit`时，就不会报错，能正常显示界面。

**Comment by cjh3020889729** [comment]
本机环境是64位的吗？看起来像是64-bits的库与当前一些项目代码不支持。

**Comment by cjh3020889729** [comment]
如果问题还没有解决，可以加微信联系一下:cjh3020889729

**Comment by geoexploring** [comment]
@cjh3020889729 ，谢谢！
